2021-09-15 19:36:16.053 [error] <0.791.0> gen_server <0.791.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat',reason => nil},[{'Elixir.RabbitChatWeb.ChatterLive.Chat','__live__',[],[]},{'Elixir.Phoenix.LiveView.Channel',verified_mount,7,[{file,"lib/phoenix_live_view/channel.ex"},{line,862}]},{'Elixir.Phoenix.LiveView.Channel',handle_info,2,[{file,"lib/phoenix_live_view/channel.ex"},{line,58}]},{gen_server,try_dispatch,4,[{file,...},...]},...]}
2021-09-15 19:36:16.057 [error] <0.791.0> CRASH REPORT Process <0.791.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat',reason => nil},[{'Elixir.RabbitChatWeb.ChatterLive.Chat','__live__',[],[]},{'Elixir.Phoenix.LiveView.Channel',verified_mount,7,[{file,"lib/phoenix_live_view/channel.ex"},{line,862}]},{'Elixir.Phoenix.LiveView.Channel',handle_info,2,[{file,"lib/phoenix_live_view/channel.ex"},{line,58}]},{gen_server,try_dispatch,4,[{file,...},...]},...]}
2021-09-15 19:36:16.057 [error] <0.621.0> Supervisor {<0.621.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.791.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat',reason => nil},[{'Elixir.RabbitChatWeb.ChatterLive.Chat','__live__',[],[]},{'Elixir.Phoenix.LiveView.Channel',verified_mount,7,[{file,"lib/phoenix_live_view/channel.ex"},{line,862}]},{'Elixir.Phoenix.LiveView.Channel',handle_info,2,[{file,"lib/phoenix_live_view/channel.ex"},{line,58}]},{gen_server,try_dispatch,4,[{file,...},...]},...]} in context child_terminated
2021-09-15 19:36:18.059 [error] <0.792.0> CRASH REPORT Process <0.792.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat',reason => nil},[{'Elixir.RabbitChatWeb.ChatterLive.Chat','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,239}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,83}]},{'Elixir.Phoenix.LiveView.Controller',live_render,...},...]},...},...},...}
2021-09-15 19:36:18.065 [error] <0.792.0> Cowboy stream 4 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.762.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat',reason => nil},[{'Elixir.RabbitChatWeb.ChatterLive.Chat','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,239}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,83}]},{'Elixir.Phoenix.LiveView.Controller',live_render,...},...]},...},...}
2021-09-15 19:36:31.510 [error] <0.803.0> CRASH REPORT Process <0.803.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/show.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/show.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:36:31.510 [error] <0.803.0> Cowboy stream 6 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.762.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/show.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/show.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:36:37.703 [error] <0.825.0> CRASH REPORT Process <0.825.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:36:37.704 [error] <0.825.0> Cowboy stream 8 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.762.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:36:47.146 [error] <0.847.0> CRASH REPORT Process <0.847.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:36:47.147 [error] <0.847.0> Cowboy stream 10 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.762.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:37:02.997 [error] <0.576.0> CRASH REPORT Process <0.576.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:37:03.000 [error] <0.576.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.575.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,19}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:38:02.364 [error] <0.601.0> CRASH REPORT Process <0.601.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:38:02.364 [error] <0.601.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.575.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:42:02.752 [error] <0.618.0> gen_server <0.618.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]}
2021-09-15 19:42:02.763 [error] <0.618.0> CRASH REPORT Process <0.618.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]}
2021-09-15 19:42:02.764 [error] <0.481.0> Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.618.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]} in context child_terminated
2021-09-15 19:42:04.235 [error] <0.619.0> CRASH REPORT Process <0.619.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:42:04.238 [error] <0.619.0> Cowboy stream 4 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:42:53.524 [error] <0.630.0> CRASH REPORT Process <0.630.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:42:53.524 [error] <0.630.0> Cowboy stream 5 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:43:08.646 [error] <0.652.0> CRASH REPORT Process <0.652.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:43:08.646 [error] <0.652.0> Cowboy stream 6 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:43:47.103 [error] <0.675.0> CRASH REPORT Process <0.675.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:43:47.104 [error] <0.675.0> Cowboy stream 7 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:44:32.778 [error] <0.697.0> CRASH REPORT Process <0.697.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:44:32.778 [error] <0.697.0> Cowboy stream 8 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:44:36.417 [error] <0.719.0> CRASH REPORT Process <0.719.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:44:36.417 [error] <0.719.0> Cowboy stream 9 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:44:40.678 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:44:40.679 [error] <0.729.0> Cowboy stream 10 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:44:48.677 [error] <0.751.0> CRASH REPORT Process <0.751.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:44:48.677 [error] <0.751.0> Cowboy stream 11 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:44:57.785 [error] <0.773.0> CRASH REPORT Process <0.773.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:44:57.786 [error] <0.773.0> Cowboy stream 12 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.598.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"new">>},<<"http://localhost:4000/chatters/new">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:55:15.502 [error] <0.650.0> CRASH REPORT Process <0.650.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"test">>},<<"http://localhost:4000/chatters/test">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:55:15.514 [error] <0.650.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"test">>},<<"http://localhost:4000/chatters/test">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:55:43.620 [error] <0.657.0> CRASH REPORT Process <0.657.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"test">>},<<"http://localhost:4000/chatters/test">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:55:43.620 [error] <0.657.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"test">>},<<"http://localhost:4000/chatters/test">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:55:59.848 [error] <0.679.0> CRASH REPORT Process <0.679.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"test">>},<<"http://localhost:4000/chatters/test">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...},...}
2021-09-15 19:55:59.848 [error] <0.679.0> Cowboy stream 5 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"id">> => <<"test">>},<<"http://localhost:4000/chatters/test">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => ...,...}],...},...]},...},...}
2021-09-15 19:56:24.345 [error] <0.689.0> CRASH REPORT Process <0.689.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:56:24.345 [error] <0.689.0> Cowboy stream 7 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:57:14.627 [error] <0.728.0> CRASH REPORT Process <0.728.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,16}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_vie..."},...]},...]},...},...},...}
2021-09-15 19:57:14.627 [error] <0.728.0> Cowboy stream 9 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,16}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_view/..."},...]},...]},...},...}
2021-09-15 19:57:41.164 [error] <0.751.0> CRASH REPORT Process <0.751.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...},...}
2021-09-15 19:57:41.164 [error] <0.751.0> Cowboy stream 11 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => page_title,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',page_title,[chat],[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,21}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',...},...]},...},...}
2021-09-15 19:58:09.876 [error] <0.773.0> CRASH REPORT Process <0.773.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,16}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_vie..."},...]},...]},...},...},...}
2021-09-15 19:58:09.877 [error] <0.773.0> Cowboy stream 13 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,16}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_view/..."},...]},...]},...},...}
2021-09-15 19:59:54.968 [error] <0.917.0>@Elixir.RabbitChatWeb.ChatterLive.Index:apply_action:24 gen_server <0.917.0> terminated with reason: no function clause matching 'Elixir.RabbitChatWeb.ChatterLive.Index':apply_action(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{live_action => ...},...},...}, new, #{}) line 24
2021-09-15 19:59:54.986 [error] <0.917.0>@Elixir.RabbitChatWeb.ChatterLive.Index:apply_action:24 CRASH REPORT Process <0.917.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RabbitChatWeb.ChatterLive.Index':apply_action(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{live_action => ...},...},...}, new, #{}) line 24
2021-09-15 19:59:54.987 [error] <0.490.0>@Elixir.RabbitChatWeb.ChatterLive.Index:apply_action:24 Supervisor {<0.490.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.917.0> exit with reason no function clause matching 'Elixir.RabbitChatWeb.ChatterLive.Index':apply_action(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{live_action => ...},...},...}, new, #{}) line 24 in context child_terminated
2021-09-15 19:59:56.675 [error] <0.922.0> CRASH REPORT Process <0.922.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => apply_action,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Index'},[{'Elixir.RabbitChatWeb.ChatterLive.Index',apply_action,[#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{chatters => true},chatters => #{},flash => #{},live_action => new},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => {nil,#{}},host_uri => #{...},...},...],...},...]},...},...},...}
2021-09-15 19:59:56.675 [error] <0.922.0> Cowboy stream 14 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.814.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => apply_action,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Index'},[{'Elixir.RabbitChatWeb.ChatterLive.Index',apply_action,[#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{chatters => true},chatters => #{},flash => #{},live_action => new},endpoint => 'Elixir.RabbitChatWeb.Endpoint',fingerprints => {nil,#{}},host_uri => #{...},...},...],...},...]},...},...}
2021-09-15 20:00:07.579 [error] <0.936.0> CRASH REPORT Process <0.936.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => nil,status => nil}},[{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,5}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',...},...]},...},...},...}
2021-09-15 20:00:07.580 [error] <0.936.0> Cowboy stream 22 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => nil,status => nil}},[{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,5}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',...},...]},...},...}
2021-09-15 20:00:28.630 [error] <0.959.0> CRASH REPORT Process <0.959.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @changeset not available in template.\n\nPlease make sure all proper assigns have been set. If you are\ncalling a component, make sure you are passing all required\nassigns as arguments.\n\nAvailable assigns: [:__changed__, :action, :chatter, :flash, :id, :myself, :return_to, :socket, :title]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,1111}]},{...},...]},...},...},...}
2021-09-15 20:00:28.630 [error] <0.959.0> Cowboy stream 24 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.647.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @changeset not available in template.\n\nPlease make sure all proper assigns have been set. If you are\ncalling a component, make sure you are passing all required\nassigns as arguments.\n\nAvailable assigns: [:__changed__, :action, :chatter, :flash, :id, :myself, :return_to, :socket, :title]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,1111}]},{'Elixir.RabbitChatWeb.ChatterLive.FormComponent',...},...]},...},...}
2021-09-15 20:00:54.511 [error] <0.992.0> CRASH REPORT Process <0.992.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"missing :for assign to form">>},[{'Elixir.Phoenix.LiveView.Helpers',form,1,[{file,"lib/phoenix_live_view/helpers.ex"},{line,929}]},{'Elixir.Phoenix.LiveView.Helpers','__component__',3,[{file,"lib/phoenix_live_view/helpers.ex"},{line,508}]},{'Elixir.RabbitChatWeb.ChatterLive.FormComponent','-render/1-fun-3-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/form_component.html.heex"},{line,1}]},{'Elixir.Phoenix.LiveView.Diff',...},...]},...},...},...}
2021-09-15 20:00:54.511 [error] <0.992.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.991.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"missing :for assign to form">>},[{'Elixir.Phoenix.LiveView.Helpers',form,1,[{file,"lib/phoenix_live_view/helpers.ex"},{line,929}]},{'Elixir.Phoenix.LiveView.Helpers','__component__',3,[{file,"lib/phoenix_live_view/helpers.ex"},{line,508}]},{'Elixir.RabbitChatWeb.ChatterLive.FormComponent','-render/1-fun-3-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/form_component.html.heex"},{line,1}]},{'Elixir.Phoenix.LiveView.Diff',...},...]},...},...}
2021-09-15 20:01:03.253 [error] <0.1012.0> CRASH REPORT Process <0.1012.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.FormData',value => #{}},[{'Elixir.Phoenix.HTML.FormData','impl_for!',1,[{file,"lib/phoenix_html/form_data.ex"},{line,1}]},{'Elixir.Phoenix.HTML.FormData',to_form,2,[{file,"lib/phoenix_html/form_data.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Helpers',form,1,[{file,"lib/phoenix_live_view/helpers.ex"},{line,935}]},{'Elixir.Phoenix.LiveView.Helpers','__component__',...},...]},...},...},...}
2021-09-15 20:01:03.253 [error] <0.1012.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.991.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.FormData',value => #{}},[{'Elixir.Phoenix.HTML.FormData','impl_for!',1,[{file,"lib/phoenix_html/form_data.ex"},{line,1}]},{'Elixir.Phoenix.HTML.FormData',to_form,2,[{file,"lib/phoenix_html/form_data.ex"},{line,15}]},{'Elixir.Phoenix.LiveView.Helpers',form,1,[{file,"lib/phoenix_live_view/helpers.ex"},{line,935}]},{'Elixir.Phoenix.LiveView.Helpers','__component__',...},...]},...},...}
2021-09-15 20:03:08.678 [error] <0.451.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:03:08.682 [error] <0.451.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:03:08.682 [error] <0.450.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.451.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:03:08.682 [error] <0.618.0> gen_server <0.618.0> terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:03:08.696 [error] <0.618.0> CRASH REPORT Process <0.618.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:03:08.696 [error] <0.472.0> Supervisor {<0.472.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.618.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in context child_terminated
2021-09-15 20:05:17.786 [error] <0.595.0> gen_server <0.595.0> terminated with reason: {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',{add_chatter,<<"myself">>},5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:05:17.827 [error] <0.595.0> CRASH REPORT Process <0.595.0> with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',{add_chatter,<<"myself">>},5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:05:17.827 [error] <0.476.0> Supervisor {<0.476.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.595.0> exit with reason {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',{add_chatter,<<"myself">>},5000]}} in context child_terminated
2021-09-15 20:05:23.843 [error] <0.598.0> gen_server <0.598.0> terminated with reason: {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:05:23.847 [error] <0.598.0> CRASH REPORT Process <0.598.0> with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:05:23.847 [error] <0.480.0> Supervisor {<0.480.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.598.0> exit with reason {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}} in context child_terminated
2021-09-15 20:05:31.386 [error] <0.601.0> CRASH REPORT Process <0.601.0> with 0 neighbours exited with reason: {{{{timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,...},...}},...},...]}},...},...}
2021-09-15 20:05:31.391 [error] <0.601.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.600.0> had its request process exit with reason: {{{timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,...},...}},...},...]}},...}
2021-09-15 20:06:04.056 [error] <0.453.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:06:04.059 [error] <0.453.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:06:04.059 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.453.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:06:04.059 [error] <0.604.0> gen_server <0.604.0> terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:06:04.074 [error] <0.604.0> CRASH REPORT Process <0.604.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:06:04.075 [error] <0.474.0> Supervisor {<0.474.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.604.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in context child_terminated
2021-09-15 20:06:59.350 [error] <0.453.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: {badkey,chatters,#{}} in 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call/3 line 38
2021-09-15 20:06:59.371 [error] <0.453.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: {badkey,chatters,#{}} in 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call/3 line 38
2021-09-15 20:06:59.371 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.453.0> exit with reason {badkey,chatters,#{}} in 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call/3 line 38 in context child_terminated
2021-09-15 20:06:59.371 [error] <0.594.0> gen_server <0.594.0> terminated with reason: {{{badkey,chatters,#{}},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,38}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:06:59.383 [error] <0.594.0> CRASH REPORT Process <0.594.0> with 0 neighbours exited with reason: {{{badkey,chatters,#{}},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,38}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:06:59.383 [error] <0.474.0> Supervisor {<0.474.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.594.0> exit with reason {{{badkey,chatters,#{}},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,38}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}} in context child_terminated
2021-09-15 20:07:01.487 [error] <0.595.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: {badkey,chatters,#{}} in 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call/3 line 38
2021-09-15 20:07:01.489 [error] <0.595.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: {badkey,chatters,#{}} in 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call/3 line 38
2021-09-15 20:07:01.489 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.595.0> exit with reason {badkey,chatters,#{}} in 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call/3 line 38 in context child_terminated
2021-09-15 20:07:01.531 [error] <0.598.0> CRASH REPORT Process <0.598.0> with 0 neighbours exited with reason: {{{{{{badkey,chatters,#{}},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,38}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,...}},...},...}
2021-09-15 20:07:01.534 [error] <0.598.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.597.0> had its request process exit with reason: {{{{{badkey,chatters,#{}},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,38}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',list_chatters,5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[...]}},...}
2021-09-15 20:08:29.130 [error] <0.453.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:08:29.134 [error] <0.453.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:08:29.135 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.453.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:08:29.135 [error] <0.602.0> gen_server <0.602.0> terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:08:29.150 [error] <0.602.0> CRASH REPORT Process <0.602.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 20:08:29.150 [error] <0.480.0> Supervisor {<0.480.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.602.0> exit with reason {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,141}]},{'Elixir.Enum',reduce,3,[{file,"lib/enum.ex"},...]},...]},...} in context child_terminated
2021-09-15 20:09:33.918 [error] <0.604.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:09:33.923 [error] <0.604.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:09:33.923 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.604.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:10:04.579 [error] <0.646.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:04.583 [error] <0.646.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:04.583 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.646.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:10:10.926 [error] <0.649.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:10.932 [error] <0.649.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:10.933 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.649.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:10:22.758 [error] <0.722.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:22.762 [error] <0.722.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:22.763 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.722.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:10:23.666 [error] <0.795.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:23.668 [error] <0.795.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2021-09-15 20:10:23.669 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.795.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => <<"%RabbitChat.ChatContext.ChattersInMemDB{chatters: %{\"myself\" => %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myself\", status: nil}}, periodic_cleaner: nil}">>} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 20:11:40.893 [error] <0.874.0> gen_server <0.874.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},{maps,...},...]}
2021-09-15 20:11:40.898 [error] <0.874.0> CRASH REPORT Process <0.874.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},{maps,...},...]}
2021-09-15 20:11:40.898 [error] <0.479.0> Supervisor {<0.479.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.874.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},{maps,...},...]} in context child_terminated
2021-09-15 20:11:43.891 [error] <0.876.0> CRASH REPORT Process <0.876.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...},...}
2021-09-15 20:11:43.899 [error] <0.876.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.875.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...}
2021-09-15 20:16:53.575 [error] <0.907.0> CRASH REPORT Process <0.907.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},id,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...},...}
2021-09-15 20:16:53.575 [error] <0.907.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.906.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},id,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...}
2021-09-15 20:16:57.200 [error] <0.930.0> CRASH REPORT Process <0.930.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},id,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...},...}
2021-09-15 20:16:57.200 [error] <0.930.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.906.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},id,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...}
2021-09-15 20:17:10.388 [error] <0.941.0> CRASH REPORT Process <0.941.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...},...}
2021-09-15 20:17:10.389 [error] <0.941.0> Cowboy stream 5 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.906.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,22}]},...]},...},...}
2021-09-15 20:19:14.709 [error] <0.966.0> CRASH REPORT Process <0.966.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,23}]},...]},...},...},...}
2021-09-15 20:19:14.709 [error] <0.966.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.965.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,23}]},...]},...},...}
2021-09-15 20:19:17.818 [error] <0.989.0> CRASH REPORT Process <0.989.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,23}]},...]},...},...},...}
2021-09-15 20:19:17.818 [error] <0.989.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.965.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myself">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myself">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,23}]},...]},...},...}
2021-09-15 20:20:23.504 [error] <0.758.0> gen_server <0.758.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2021-09-15 20:20:23.513 [error] <0.758.0> CRASH REPORT Process <0.758.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2021-09-15 20:20:23.513 [error] <0.456.0> Supervisor {<0.456.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.758.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99 in context child_terminated
2021-09-15 20:20:25.423 [error] <0.759.0> CRASH REPORT Process <0.759.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}}},[{'Elixir.Phoenix.HTML.Safe.Tuple',to_iodata,1,[{file,"lib/phoenix_html/safe.ex"},{line,99}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html..."},...]},...]},...},...},...}
2021-09-15 20:20:25.426 [error] <0.759.0> Cowboy stream 9 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.613.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}}},[{'Elixir.Phoenix.HTML.Safe.Tuple',to_iodata,1,[{file,"lib/phoenix_html/safe.ex"},{line,99}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.h..."},...]},...]},...},...}
2021-09-15 20:20:41.792 [error] <0.770.0> CRASH REPORT Process <0.770.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,...}]},...]},...},...},...}
2021-09-15 20:20:41.793 [error] <0.770.0> Cowboy stream 10 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.613.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,...}]},...]},...},...}
2021-09-15 20:21:33.145 [error] <0.853.0> CRASH REPORT Process <0.853.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,...}]},...]},...},...},...}
2021-09-15 20:21:33.146 [error] <0.853.0> Cowboy stream 16 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.632.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"errors were found at the given arguments:\n\n  * 1st argument: not an atom\n">>},[{erlang,apply,[{<<"myselfff">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"myselfff">>,status => nil}},name,[]],[{error_info,#{module => erl_erts_errors}}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index.html.heex"},{line,...}]},...]},...},...}
2021-09-15 20:22:07.808 [error] <0.612.0> gen_server <0.612.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :show for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 368
2021-09-15 20:22:07.817 [error] <0.612.0> CRASH REPORT Process <0.612.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :show for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 368
2021-09-15 20:22:07.817 [error] <0.473.0> Supervisor {<0.473.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.612.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :show for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>} in 'Elixir.Phoenix.Router.Helpers':invalid_route_error/3 line 368 in context child_terminated
2021-09-15 20:22:10.689 [error] <0.613.0> CRASH REPORT Process <0.613.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :show for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/inde..."},...]},...]},...},...},...}
2021-09-15 20:22:10.693 [error] <0.613.0> Cowboy stream 4 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.600.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :show for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index...."},...]},...]},...},...}
2021-09-15 20:22:23.454 [error] <0.628.0> CRASH REPORT Process <0.628.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :chat for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/inde..."},...]},...]},...},...},...}
2021-09-15 20:22:23.454 [error] <0.628.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.592.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :chat for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index...."},...]},...]},...},...}
2021-09-15 20:22:27.417 [error] <0.650.0> CRASH REPORT Process <0.650.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :chat for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/inde..."},...]},...]},...},...},...}
2021-09-15 20:22:27.417 [error] <0.650.0> Cowboy stream 5 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.592.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :chat for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index...."},...]},...]},...},...}
2021-09-15 20:22:29.008 [error] <0.660.0> CRASH REPORT Process <0.660.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :chat for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/inde..."},...]},...]},...},...},...}
2021-09-15 20:22:29.009 [error] <0.660.0> Cowboy stream 7 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.592.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :chat for RabbitChatWeb.Router.Helpers.chatter_show_path/3. The following actions/clauses are supported:\n\n    chatter_show_path(conn_or_endpoint, :edit, id, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-1-',3,[{file,"lib/rabbit_chat_web/live/chatter_live/index...."},...]},...]},...},...}
2021-09-15 20:22:44.179 [error] <0.671.0> CRASH REPORT Process <0.671.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"structs expect an :id key when converting to_param or a custom implementation of the Phoenix.Param protocol (read Phoenix.Param docs for more information), got: %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myselfff\", status: nil}">>},[{'Elixir.Phoenix.Param.Any',to_param,1,[{file,"lib/phoenix/param.ex"},{line,118}]},{'Elixir.RabbitChatWeb.Router.Helpers',chatter_chat_path,4,[]},{'Elixir.RabbitChatWeb.ChatterLive.Index',...},...]},...},...},...}
2021-09-15 20:22:44.179 [error] <0.671.0> Cowboy stream 9 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.592.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"structs expect an :id key when converting to_param or a custom implementation of the Phoenix.Param protocol (read Phoenix.Param docs for more information), got: %RabbitChat.ChatContext.Chatter{last_login: nil, name: \"myselfff\", status: nil}">>},[{'Elixir.Phoenix.Param.Any',to_param,1,[{file,"lib/phoenix/param.ex"},{line,118}]},{'Elixir.RabbitChatWeb.Router.Helpers',chatter_chat_path,4,[]},{'Elixir.RabbitChatWeb.ChatterLive.Index',...},...]},...},...}
2021-09-15 20:26:16.541 [error] <0.796.0> CRASH REPORT Process <0.796.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index...."},...]},...]},...},...},...}
2021-09-15 20:26:16.544 [error] <0.796.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.795.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index.ht..."},...]},...]},...},...}
2021-09-15 20:26:26.679 [error] <0.574.0> CRASH REPORT Process <0.574.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index...."},...]},...]},...},...},...}
2021-09-15 20:26:26.681 [error] <0.574.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.573.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index.ht..."},...]},...]},...},...}
2021-09-15 20:35:52.551 [error] <0.590.0> CRASH REPORT Process <0.590.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"from">> => <<"wannes">>,<<"to">> => <<"tom">>},<<"http://localhost:4000/chatters/wannes/tom/chat">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',...}],...},...]},...},...},...}
2021-09-15 20:35:52.552 [error] <0.590.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.589.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => handle_params,kind => nil,module => 'Elixir.RabbitChatWeb.ChatterLive.Chat'},[{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,[#{<<"from">> => <<"wannes">>,<<"to">> => <<"tom">>},<<"http://localhost:4000/chatters/wannes/tom/chat">>,#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},flash => #{},live_action => chat},endpoint => 'Elixir.RabbitChatWeb.Endpoint',...}],...},...]},...},...}
2021-09-15 20:37:04.062 [error] <0.632.0> CRASH REPORT Process <0.632.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ht..."},...]},...]},...},...},...}
2021-09-15 20:37:04.062 [error] <0.632.0> Cowboy stream 5 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.589.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html..."},...]},...]},...},...}
2021-09-15 20:38:00.093 [error] <0.595.0> CRASH REPORT Process <0.595.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ht..."},...]},...]},...},...},...}
2021-09-15 20:38:00.096 [error] <0.595.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.594.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-1-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html..."},...]},...]},...},...}
2021-09-15 20:43:47.217 [error] <0.755.0> CRASH REPORT Process <0.755.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @from not available in template.\n\nPlease make sure all proper assigns have been set. If you are\ncalling a component, make sure you are passing all required\nassigns as arguments.\n\nAvailable assigns: [:__changed__, :current_chatter, :destination_chatter, :flash, :live_action, :page_title, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,...}]},...]},...},...},...}
2021-09-15 20:43:47.217 [error] <0.755.0> Cowboy stream 6 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.715.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @from not available in template.\n\nPlease make sure all proper assigns have been set. If you are\ncalling a component, make sure you are passing all required\nassigns as arguments.\n\nAvailable assigns: [:__changed__, :current_chatter, :destination_chatter, :flash, :live_action, :page_title, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,1111}]},...]},...},...}
2021-09-15 20:44:10.017 [error] <0.778.0> CRASH REPORT Process <0.778.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-3-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,3}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_view..."},...]},...]},...},...},...}
2021-09-15 20:44:10.017 [error] <0.778.0> Cowboy stream 8 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.715.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-3-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,3}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_view/d..."},...]},...]},...},...}
2021-09-15 20:44:32.950 [error] <0.801.0> CRASH REPORT Process <0.801.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index...."},...]},...]},...},...},...}
2021-09-15 20:44:32.951 [error] <0.801.0> Cowboy stream 10 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.715.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no action :index for RabbitChatWeb.Router.Helpers.chatter_index_path/2. The following actions/clauses are supported:\n\n    chatter_index_path(conn_or_endpoint, :new, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',invalid_route_error,3,[{file,"lib/phoenix/router/helpers.ex"},{line,368}]},{'Elixir.RabbitChatWeb.ChatterLive.Index','-render/1-fun-0-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/index.ht..."},...]},...]},...},...}
2021-09-15 20:45:10.631 [error] <0.820.0> CRASH REPORT Process <0.820.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @myself not available in template.\n\nPlease make sure all proper assigns have been set. If you are\ncalling a component, make sure you are passing all required\nassigns as arguments.\n\nAvailable assigns: [:__changed__, :current_chatter, :destination_chatter, :flash, :live_action, :page_title, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,...}]},...]},...},...},...}
2021-09-15 20:45:10.631 [error] <0.820.0> Cowboy stream 12 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.715.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @myself not available in template.\n\nPlease make sure all proper assigns have been set. If you are\ncalling a component, make sure you are passing all required\nassigns as arguments.\n\nAvailable assigns: [:__changed__, :current_chatter, :destination_chatter, :flash, :live_action, :page_title, :socket]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,...}]},...]},...},...}
2021-09-15 20:46:35.968 [error] <0.833.0> CRASH REPORT Process <0.833.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"wannes">>,status => nil}},[{'Elixir.Phoenix.HTML.Safe','impl_for!',1,[{file,"lib/phoenix_html/safe.ex"},{line,1}]},{'Elixir.Phoenix.HTML.Safe',to_iodata,1,[{file,"lib/phoenix_html/safe.ex"},{line,15}]},{'Elixir.Phoenix.HTML.Tag',build_attrs,1,[{file,"lib/pho..."},...]},...]},...},...},...}
2021-09-15 20:46:35.969 [error] <0.833.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.832.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"wannes">>,status => nil}},[{'Elixir.Phoenix.HTML.Safe','impl_for!',1,[{file,"lib/phoenix_html/safe.ex"},{line,1}]},{'Elixir.Phoenix.HTML.Safe',to_iodata,1,[{file,"lib/phoenix_html/safe.ex"},{line,15}]},{'Elixir.Phoenix.HTML.Tag',build_attrs,1,[{file,"lib/phoen..."},...]},...]},...},...}
2021-09-15 20:49:18.362 [error] <0.1036.0>@Elixir.Phoenix.LiveView.Channel:-view_handle_event/3-fun-0-:349 gen_server <0.1036.0> terminated with reason: call to undefined function 'Elixir.RabbitChatWeb.ChatterLive.Chat':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':'-view_handle_event/3-fun-0-'/3 line 349
2021-09-15 20:49:18.368 [error] <0.1036.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:handle_event CRASH REPORT Process <0.1036.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RabbitChatWeb.ChatterLive.Chat':handle_event(<<"save">>, #{<<"_csrf_token">> => <<"LGA8PDAxJTUHHzQmJCVRQQJiZCRKMiQiF7ozCPmwMMkRgMg-aVSOsxSv">>,<<"mess...">> => ...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},current_chatter => ...,...},...})
2021-09-15 20:49:18.368 [error] <0.482.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:handle_event Supervisor {<0.482.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.1036.0> exit with reason call to undefined function 'Elixir.RabbitChatWeb.ChatterLive.Chat':handle_event(<<"save">>, #{<<"_csrf_token">> => <<"LGA8PDAxJTUHHzQmJCVRQQJiZCRKMiQiF7ozCPmwMMkRgMg-aVSOsxSv">>,<<"mess...">> => ...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},current_chatter => ...,...},...}) in context child_terminated
2021-09-15 20:53:09.893 [error] <0.1072.0> gen_server <0.1072.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from RabbitChatWeb.ChatterLive.Chat.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: :ok\n">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 454
2021-09-15 20:53:09.894 [error] <0.1072.0> CRASH REPORT Process <0.1072.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from RabbitChatWeb.ChatterLive.Chat.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: :ok\n">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 454
2021-09-15 20:53:09.895 [error] <0.483.0> Supervisor {<0.483.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.1072.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from RabbitChatWeb.ChatterLive.Chat.handle_event/3 callback.\n\nExpected one of:\n\n    {:noreply, %Socket{}}\n    {:reply, map, %Socket{}}\n\nGot: :ok\n">>} in 'Elixir.Phoenix.LiveView.Channel':'raise_bad_callback_response!'/4 line 454 in context child_terminated
2021-09-15 20:58:35.987 [error] <0.1321.0> gen_server <0.1321.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{<<"message">> => <<"test">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1
2021-09-15 20:58:35.990 [error] <0.1321.0> CRASH REPORT Process <0.1321.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{<<"message">> => <<"test">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1
2021-09-15 20:58:35.991 [error] <0.486.0> Supervisor {<0.486.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.1321.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{<<"message">> => <<"test">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 21:05:18.228 [error] <0.592.0> CRASH REPORT Process <0.592.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-4-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,3}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_view..."},...]},...]},...},...},...}
2021-09-15 21:05:18.232 [error] <0.592.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.591.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => name,message => nil,module => nil,reason => nil},[{nil,name,[],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat','-render/1-fun-4-',2,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.html.heex"},{line,3}]},{'Elixir.Phoenix.LiveView.Diff',traverse,6,[{file,"lib/phoenix_live_view/diff.ex"},{line,370}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/6-fun-0-',4,[{file,"lib/phoenix_live_view/d..."},...]},...]},...},...}
2021-09-15 21:18:15.566 [error] <0.453.0>@Elixir.RabbitChat.ChatContext.ChattersInMemDB:handle_call:31 gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: no function clause matching 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call({report_pid,<<"a">>,<0.634.0>}, {<0.634.0>,[alias|#Ref<0.47281988.3550806018.229103>]}, #{'__struct__' => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',chatters => #{<<"a">> => #{'__struct__' => ...,...},...},...}) line 31
2021-09-15 21:18:15.600 [error] <0.453.0>@Elixir.RabbitChat.ChatContext.ChattersInMemDB:handle_call:31 CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: no function clause matching 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call({report_pid,<<"a">>,<0.634.0>}, {<0.634.0>,[alias|#Ref<0.47281988.3550806018.229103>]}, #{'__struct__' => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',chatters => #{<<"a">> => #{'__struct__' => ...,...},...},...}) line 31
2021-09-15 21:18:15.601 [error] <0.452.0>@Elixir.RabbitChat.ChatContext.ChattersInMemDB:handle_call:31 Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.453.0> exit with reason no function clause matching 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':handle_call({report_pid,<<"a">>,<0.634.0>}, {<0.634.0>,[alias|#Ref<0.47281988.3550806018.229103>]}, #{'__struct__' => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',chatters => #{<<"a">> => #{'__struct__' => ...,...},...},...}) line 31 in context child_terminated
2021-09-15 21:18:15.683 [error] <0.634.0> CRASH REPORT Process <0.634.0> with 0 neighbours exited with reason: {{{{{function_clause,[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,[{report_pid,<<"a">>,<0.634.0>},{<0.634.0>,[alias|#Ref<0.47281988.3550806018.229103>]},#{'__struct__' => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',chatters => #{<<"a">> => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil},<<"b">> => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"b">>,status => nil},<<"...">> => ...,...},...}],...},...]},...},...},...},...}
2021-09-15 21:18:15.688 [error] <0.634.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.633.0> had its request process exit with reason: {{{{function_clause,[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,[{report_pid,<<"a">>,<0.634.0>},{<0.634.0>,[alias|#Ref<0.47281988.3550806018.229103>]},#{'__struct__' => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',chatters => #{<<"a">> => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil},<<"b">> => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"b">>,status => nil},<<"...">> => ...,...},...}],...},...]},...},...},...}
2021-09-15 21:18:19.832 [error] <0.661.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: {badmap,nil} in 'Elixir.Map':put_new/3 line 300
2021-09-15 21:18:19.835 [error] <0.661.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: {badmap,nil} in 'Elixir.Map':put_new/3 line 300
2021-09-15 21:18:19.836 [error] <0.452.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.661.0> exit with reason {badmap,nil} in 'Elixir.Map':put_new/3 line 300 in context child_terminated
2021-09-15 21:18:19.851 [error] <0.666.0> CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: {{{{{{badmap,nil},[{'Elixir.Map',put_new,3,[{file,"lib/map.ex"},{line,300}]},{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,51}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',{report_pid,...},...]}},...},...},...}
2021-09-15 21:18:19.851 [error] <0.666.0> Cowboy stream 2 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.633.0> had its request process exit with reason: {{{{{badmap,nil},[{'Elixir.Map',put_new,3,[{file,"lib/map.ex"},{line,300}]},{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,51}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',{report_pid,...},...]}},...},...}
2021-09-15 21:18:28.620 [error] <0.434.0> gen_server 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' terminated with reason: {badmap,nil} in 'Elixir.Map':put_new/3 line 300
2021-09-15 21:18:28.633 [error] <0.434.0> CRASH REPORT Process 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' with 0 neighbours crashed with reason: {badmap,nil} in 'Elixir.Map':put_new/3 line 300
2021-09-15 21:18:28.633 [error] <0.433.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.ChatContext.ChattersInMemDB' started with 'Elixir.RabbitChat.ChatContext.ChattersInMemDB':start_link([]) at <0.434.0> exit with reason {badmap,nil} in 'Elixir.Map':put_new/3 line 300 in context child_terminated
2021-09-15 21:18:28.670 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: {{{{{{badmap,nil},[{'Elixir.Map',put_new,3,[{file,"lib/map.ex"},{line,300}]},{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,51}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',{report_pid,...},...]}},...},...},...}
2021-09-15 21:18:28.677 [error] <0.570.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.569.0> had its request process exit with reason: {{{{{badmap,nil},[{'Elixir.Map',put_new,3,[{file,"lib/map.ex"},{line,300}]},{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',handle_call,3,[{file,"lib/rabbit_chat/chat_context/chatters_in_mem_db.ex"},{line,51}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,721}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,750}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.RabbitChat.ChatContext.ChattersInMemDB',{report_pid,...},...]}},...},...}
2021-09-15 21:19:28.605 [error] <0.603.0> gen_server <0.603.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => fetch,message => nil,module => 'Elixir.RabbitChat.ChatContext.Message',reason => <<"RabbitChat.ChatContext.Message does not implement the Access behaviour">>},[{'Elixir.RabbitChat.ChatContext.Message',fetch,[#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"b">>,status => nil},message => <<..>>,...},...],...},...]}
2021-09-15 21:19:28.613 [error] <0.603.0> CRASH REPORT Process <0.603.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => fetch,message => nil,module => 'Elixir.RabbitChat.ChatContext.Message',reason => <<"RabbitChat.ChatContext.Message does not implement the Access behaviour">>},[{'Elixir.RabbitChat.ChatContext.Message',fetch,[#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"b">>,status => nil},message => <<..>>,...},...],...},...]}
2021-09-15 21:19:28.615 [error] <0.478.0> Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.603.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => fetch,message => nil,module => 'Elixir.RabbitChat.ChatContext.Message',reason => <<"RabbitChat.ChatContext.Message does not implement the Access behaviour">>},[{'Elixir.RabbitChat.ChatContext.Message',fetch,[#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"b">>,status => nil},message => <<..>>,...},...],...},...]} in context child_terminated
2021-09-15 21:20:54.325 [error] <0.662.0> gen_server <0.662.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-09-15 21:20:54.327 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-09-15 21:20:54.327 [error] <0.476.0> Supervisor {<0.476.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.662.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2021-09-15 21:48:20.641 [error] <0.612.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 gen_server <0.612.0> terminated with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:48:20.668 [error] <0.612.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 CRASH REPORT Process <0.612.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:48:20.668 [error] <0.477.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.612.0> exit with reason bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10 in context child_terminated
2021-09-15 21:48:43.633 [error] <0.623.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 gen_server <0.623.0> terminated with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:48:43.640 [error] <0.623.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 CRASH REPORT Process <0.623.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:48:43.644 [error] <0.478.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 Supervisor {<0.478.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.623.0> exit with reason bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10 in context child_terminated
2021-09-15 21:49:42.042 [error] <0.647.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 gen_server <0.647.0> terminated with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:49:42.048 [error] <0.647.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 CRASH REPORT Process <0.647.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:49:42.048 [error] <0.477.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 Supervisor {<0.477.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.647.0> exit with reason bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10 in context child_terminated
2021-09-15 21:49:45.685 [error] <0.652.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 gen_server <0.652.0> terminated with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:49:45.688 [error] <0.652.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 CRASH REPORT Process <0.652.0> with 0 neighbours crashed with reason: bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10
2021-09-15 21:49:45.688 [error] <0.482.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:-render/1-fun-0-:10 Supervisor {<0.482.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.652.0> exit with reason bad argument in call to erlang:apply(<<"a">>, name, []) in 'Elixir.RabbitChatWeb.ChatterLive.Chat':'-render/1-fun-0-'/2 line 10 in context child_terminated
2021-09-15 21:51:08.690 [error] <0.742.0> gen_server <0.742.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"t">>,sender => <<"a">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1
2021-09-15 21:51:08.691 [error] <0.742.0> CRASH REPORT Process <0.742.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"t">>,sender => <<"a">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1
2021-09-15 21:51:08.692 [error] <0.481.0> Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.742.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"t">>,sender => <<"a">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 21:51:29.877 [error] <0.792.0> gen_server <0.792.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"test">>,sender => <<"a">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1
2021-09-15 21:51:29.878 [error] <0.792.0> CRASH REPORT Process <0.792.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"test">>,sender => <<"a">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1
2021-09-15 21:51:29.878 [error] <0.482.0> Supervisor {<0.482.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.792.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"test">>,sender => <<"a">>}} in 'Elixir.Phoenix.HTML.Safe':'impl_for!'/1 line 1 in context child_terminated
2021-09-15 21:53:36.601 [error] <0.482.0>@lists:reverse:147 CRASH REPORT Process <0.482.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"te...">>,...}) line 147
2021-09-15 21:53:36.601 [error] <0.475.0>@lists:reverse:147 Supervisor {<0.475.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.480.0>, {<<"client 192.168.0.10:58884 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.482.0> exit with reason no function clause matching lists:reverse(#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"te...">>,...}) line 147 in context child_terminated
2021-09-15 21:53:36.602 [error] <0.475.0> Supervisor {<0.475.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.480.0>, {<<"client 192.168.0.10:58884 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.482.0> exit with reason reached_max_restart_intensity in context shutdown
2021-09-15 21:53:36.663 [error] <0.446.0> gen_server 'Elixir.AMQP.Application.Channel::produce_channel' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.639.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 21:53:36.671 [error] <0.446.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::produce_channel' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.639.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 21:53:36.671 [error] <0.443.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::produce_channel' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,pub_tcp_connection},{proc_name,produce_channel}]) at <0.446.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.639.0>,open,70000]}} in context child_terminated
2021-09-15 21:54:05.106 [error] <0.462.0>@lists:reverse:147 Supervisor {<0.462.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.465.0>, {<<"client 192.168.0.10:58912 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.467.0> exit with reason no function clause matching lists:reverse(#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"te...">>,...}) line 147 in context child_terminated
2021-09-15 21:54:05.106 [error] <0.462.0> Supervisor {<0.462.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.465.0>, {<<"client 192.168.0.10:58912 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.467.0> exit with reason reached_max_restart_intensity in context shutdown
2021-09-15 21:54:05.109 [error] emulator Error in process <0.467.0> with exit value:
{function_clause,[{lists,reverse,[#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"b">>,message => <<"test">>,sender => <<"a">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-09-15 21:54:05.142 [error] <0.432.0> gen_server 'Elixir.AMQP.Application.Channel::produce_channel' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.628.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 21:54:05.144 [error] <0.432.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::produce_channel' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.628.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 21:54:05.145 [error] <0.429.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::produce_channel' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,pub_tcp_connection},{proc_name,produce_channel}]) at <0.432.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.628.0>,open,70000]}} in context child_terminated
2021-09-15 21:56:30.941 [error] <0.442.0>@gen_server:call gen_server 'Elixir.RabbitChat.OTP.MessagePublisher' terminated with reason: no such process or port in call to gen_server:call(<0.465.0>, {call,{'basic.publish',0,<<"wannes-chat-exchange">>,<<"a-private-messages">>,false,false},{amqp_msg,...},...}, 70000) in gen_server:call/3 line 247
2021-09-15 21:56:30.942 [error] <0.442.0>@gen_server:call CRASH REPORT Process 'Elixir.RabbitChat.OTP.MessagePublisher' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.465.0>, {call,{'basic.publish',0,<<"wannes-chat-exchange">>,<<"a-private-messages">>,false,false},{amqp_msg,...},...}, 70000) in gen_server:call/3 line 247
2021-09-15 21:56:30.943 [error] <0.440.0>@gen_server:call Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.MessagePublisher' started with 'Elixir.RabbitChat.OTP.MessagePublisher':start_link([]) at <0.442.0> exit with reason no such process or port in call to gen_server:call(<0.465.0>, {call,{'basic.publish',0,<<"wannes-chat-exchange">>,<<"a-private-messages">>,false,false},{amqp_msg,...},...}, 70000) in context child_terminated
2021-09-15 21:57:36.113 [error] <0.457.0> Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.MessagePublisher' started with 'Elixir.RabbitChat.OTP.MessagePublisher':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'wannes-chat-exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.485.0>,{call,{'exchange.declare',0,<<"wannes-chat-exchange">>,<<"direct">>,false,false,false,false,false,[]},none,<0.459.0>},70000]}} in context start_error
2021-09-15 21:57:36.114 [error] <0.455.0> CRASH REPORT Process <0.455.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.RabbitChat.OTP.MessagePublisher',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'wannes-chat-exchange' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.485.0>,{call,{'exchange.declare',0,<<"wannes-chat-exchange">>,<<"direct">>,false,false,false,false,false,[]},none,<0.459.0>},70000]}}}},{'Elixir.RabbitChat.Application',start,[normal,[]]}} in application_master:init/4 line 142
2021-09-15 22:10:34.684 [error] <0.656.0>@lists:reverse:147 Supervisor {<0.656.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.10>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.660.0>, {<<"client 192.168.0.10:59296 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.662.0> exit with reason no function clause matching lists:reverse(#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"a">>,message => <<"te...">>,...}) line 147 in context child_terminated
2021-09-15 22:10:34.684 [error] emulator Error in process <0.662.0> with exit value:
{function_clause,[{lists,reverse,[#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"a">>,message => <<"test">>,sender => <<"b">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-09-15 22:10:34.687 [error] <0.656.0> Supervisor {<0.656.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.10>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.660.0>, {<<"client 192.168.0.10:59296 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.662.0> exit with reason reached_max_restart_intensity in context shutdown
2021-09-15 22:10:34.712 [error] <0.626.0> gen_server 'Elixir.AMQP.Application.Channel::produce_channel' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.819.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 22:10:34.713 [error] <0.626.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::produce_channel' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.819.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 22:10:34.713 [error] <0.623.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::produce_channel' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,pub_tcp_connection},{proc_name,produce_channel}]) at <0.626.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.819.0>,open,70000]}} in context child_terminated
2021-09-15 22:11:07.323 [error] <0.660.0>@lists:reverse:147 CRASH REPORT Process <0.660.0> with 0 neighbours crashed with reason: no function clause matching lists:reverse(#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"a">>,message => <<"te...">>,...}) line 147
2021-09-15 22:11:07.323 [error] <0.654.0>@lists:reverse:147 Supervisor {<0.654.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.658.0>, {<<"client 192.168.0.10:59344 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.660.0> exit with reason no function clause matching lists:reverse(#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"a">>,message => <<"te...">>,...}) line 147 in context child_terminated
2021-09-15 22:11:07.323 [error] <0.654.0> Supervisor {<0.654.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.9>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.658.0>, {<<"client 192.168.0.10:59344 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.660.0> exit with reason reached_max_restart_intensity in context shutdown
2021-09-15 22:11:07.353 [error] <0.625.0> gen_server 'Elixir.AMQP.Application.Channel::produce_channel' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.813.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 22:11:07.357 [error] <0.625.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::produce_channel' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.813.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 22:11:07.357 [error] <0.622.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::produce_channel' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,pub_tcp_connection},{proc_name,produce_channel}]) at <0.625.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.813.0>,open,70000]}} in context child_terminated
2021-09-15 22:11:51.503 [error] <0.632.0>@gen_server:call gen_server 'Elixir.RabbitChat.OTP.MessagePublisher' terminated with reason: no such process or port in call to gen_server:call(<0.658.0>, {call,{'basic.publish',0,<<"wannes-chat-exchange">>,<<"a-private-messages">>,false,false},{amqp_msg,...},...}, 70000) in gen_server:call/3 line 247
2021-09-15 22:11:51.504 [error] <0.632.0>@gen_server:call CRASH REPORT Process 'Elixir.RabbitChat.OTP.MessagePublisher' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.658.0>, {call,{'basic.publish',0,<<"wannes-chat-exchange">>,<<"a-private-messages">>,false,false},{amqp_msg,...},...}, 70000) in gen_server:call/3 line 247
2021-09-15 22:11:51.504 [error] <0.630.0>@gen_server:call Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.MessagePublisher' started with 'Elixir.RabbitChat.OTP.MessagePublisher':start_link([]) at <0.632.0> exit with reason no such process or port in call to gen_server:call(<0.658.0>, {call,{'basic.publish',0,<<"wannes-chat-exchange">>,<<"a-private-messages">>,false,false},{amqp_msg,...},...}, 70000) in context child_terminated
2021-09-15 22:11:53.287 [error] <0.825.0>@lists:reverse:147 Supervisor {<0.825.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.827.0>, {<<"client 192.168.0.10:59356 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.828.0> exit with reason no function clause matching lists:reverse(#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"a">>,message => <<"te...">>,...}) line 147 in context child_terminated
2021-09-15 22:11:53.288 [error] <0.825.0> Supervisor {<0.825.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.17>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.827.0>, {<<"client 192.168.0.10:59356 -> 3.67.177.249:5672">>,1}, false, 1000000000) at <0.828.0> exit with reason reached_max_restart_intensity in context shutdown
2021-09-15 22:11:53.288 [error] emulator Error in process <0.828.0> with exit value:
{function_clause,[{lists,reverse,[#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<"a">>,message => <<"test">>,sender => <<"b">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,72}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,61}]},{rabbit_writer,assemble_frames,5,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,331}]},{rabbit_writer,internal_send_command_async,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,362}]},{rabbit_writer,handle_message,3,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,229}]},{rabbit_writer,mainloop1,2,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,213}]},{rabbit_writer,mainloop,2,[{file,"/home/wannes/Desktop/books/rabbit_chat/rabbit_chat/deps/rabbit_common/src/rabbit_writer.erl"},{line,204}]}]}
2021-09-15 22:11:53.314 [error] <0.815.0> gen_server 'Elixir.AMQP.Application.Channel::produce_channel' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.832.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 22:11:53.314 [error] <0.815.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::produce_channel' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.832.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-15 22:11:53.315 [error] <0.622.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::produce_channel' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,pub_tcp_connection},{proc_name,produce_channel}]) at <0.815.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.832.0>,open,70000]}} in context child_terminated
2021-09-15 22:13:39.396 [error] <0.459.0>@Elixir.RabbitChat.OTP.MessagePublisher:handle_cast:25 gen_server 'Elixir.RabbitChat.OTP.MessagePublisher' terminated with reason: no function clause matching 'Elixir.RabbitChat.OTP.MessagePublisher':handle_cast({publish_message,<<"a">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<...>>,...}}, #{'__struct__' => 'Elixir.RabbitChat.OTP.MessagePublisher',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...}}) line 25
2021-09-15 22:13:39.423 [error] <0.459.0>@Elixir.RabbitChat.OTP.MessagePublisher:handle_cast:25 CRASH REPORT Process 'Elixir.RabbitChat.OTP.MessagePublisher' with 0 neighbours crashed with reason: no function clause matching 'Elixir.RabbitChat.OTP.MessagePublisher':handle_cast({publish_message,<<"a">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<...>>,...}}, #{'__struct__' => 'Elixir.RabbitChat.OTP.MessagePublisher',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...}}) line 25
2021-09-15 22:13:39.423 [error] <0.457.0>@Elixir.RabbitChat.OTP.MessagePublisher:handle_cast:25 Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.MessagePublisher' started with 'Elixir.RabbitChat.OTP.MessagePublisher':start_link([]) at <0.459.0> exit with reason no function clause matching 'Elixir.RabbitChat.OTP.MessagePublisher':handle_cast({publish_message,<<"a">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<...>>,...}}, #{'__struct__' => 'Elixir.RabbitChat.OTP.MessagePublisher',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...}}) line 25 in context child_terminated
2021-09-15 22:13:50.579 [error] <0.637.0>@Elixir.RabbitChat.OTP.MessagePublisher:handle_cast:25 gen_server 'Elixir.RabbitChat.OTP.MessagePublisher' terminated with reason: no function clause matching 'Elixir.RabbitChat.OTP.MessagePublisher':handle_cast({publish_message,<<"a">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<...>>,...}}, #{'__struct__' => 'Elixir.RabbitChat.OTP.MessagePublisher',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...}}) line 25
2021-09-15 22:13:50.579 [error] <0.637.0>@Elixir.RabbitChat.OTP.MessagePublisher:handle_cast:25 CRASH REPORT Process 'Elixir.RabbitChat.OTP.MessagePublisher' with 0 neighbours crashed with reason: no function clause matching 'Elixir.RabbitChat.OTP.MessagePublisher':handle_cast({publish_message,<<"a">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<...>>,...}}, #{'__struct__' => 'Elixir.RabbitChat.OTP.MessagePublisher',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...}}) line 25
2021-09-15 22:13:50.579 [error] <0.457.0>@Elixir.RabbitChat.OTP.MessagePublisher:handle_cast:25 Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.MessagePublisher' started with 'Elixir.RabbitChat.OTP.MessagePublisher':start_link([]) at <0.637.0> exit with reason no function clause matching 'Elixir.RabbitChat.OTP.MessagePublisher':handle_cast({publish_message,<<"a">>,#{'__struct__' => 'Elixir.RabbitChat.ChatContext.Message',destination => <<...>>,...}}, #{'__struct__' => 'Elixir.RabbitChat.OTP.MessagePublisher',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...}}) line 25 in context child_terminated
2021-09-15 22:27:39.409 [error] <0.651.0> gen_server <0.651.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"b">>,<0.651.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoenix_l..."},...]},...]}
2021-09-15 22:27:39.423 [error] <0.651.0> CRASH REPORT Process <0.651.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"b">>,<0.651.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoenix_l..."},...]},...]}
2021-09-15 22:27:39.423 [error] <0.532.0> Supervisor {<0.532.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.651.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"b">>,<0.651.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoenix_l..."},...]},...]} in context child_terminated
2021-09-15 22:27:39.514 [error] <0.660.0> gen_server <0.660.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"a">>,<0.660.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoenix_l..."},...]},...]}
2021-09-15 22:27:39.514 [error] <0.660.0> CRASH REPORT Process <0.660.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"a">>,<0.660.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoenix_l..."},...]},...]}
2021-09-15 22:27:39.514 [error] <0.532.0> Supervisor {<0.532.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.660.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"a">>,<0.660.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoenix_l..."},...]},...]} in context child_terminated
2021-09-15 22:27:41.111 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"b">>,<0.662.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/pho..."},...]},...]},...},...},...}
2021-09-15 22:27:41.116 [error] <0.662.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.661.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"b">>,<0.662.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoen..."},...]},...]},...},...}
2021-09-15 22:27:41.583 [error] <0.673.0> CRASH REPORT Process <0.673.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"a">>,<0.673.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/pho..."},...]},...]},...},...},...}
2021-09-15 22:27:41.584 [error] <0.673.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.661.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => report_pid,message => nil,module => 'Elixir.RabbitChat.ChatContext.ChattersInMemDB',reason => nil},[{'Elixir.RabbitChat.ChatContext.ChattersInMemDB',report_pid,[<<"a">>,<0.673.0>],[]},{'Elixir.RabbitChatWeb.ChatterLive.Chat',handle_params,3,[{file,"lib/rabbit_chat_web/live/chatter_live/chat.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','-call_handle_params!/4-fun-0-',4,[{file,"lib/phoen..."},...]},...]},...},...}
2021-09-15 22:29:04.511 [error] <0.681.0> CRASH REPORT Process <0.681.0> with 0 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"b">>,<0.681.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"e...">>,...},...}},...},...]}},...},...}
2021-09-15 22:29:04.511 [error] <0.681.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.680.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"b">>,<0.681.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-...">>,...},...}},...},...]}},...}
2021-09-15 22:29:05.158 [error] <0.704.0> CRASH REPORT Process <0.704.0> with 0 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"a">>,<0.704.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"e...">>,...},...}},...},...]}},...},...}
2021-09-15 22:29:05.158 [error] <0.704.0> Cowboy stream 2 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.680.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"a">>,<0.704.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-...">>,...},...}},...},...]}},...}
2021-09-15 22:29:14.306 [error] <0.607.0> CRASH REPORT Process <0.607.0> with 0 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"b">>,<0.607.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"e...">>,...},...}},...},...]}},...},...}
2021-09-15 22:29:14.310 [error] <0.607.0> Cowboy stream 1 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.606.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"b">>,<0.607.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-...">>,...},...}},...},...]}},...}
2021-09-15 22:30:01.000 [error] <0.453.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 gen_server 'Elixir.RabbitChat.OTP.DynamicConsumerManager' terminated with reason: no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48
2021-09-15 22:30:01.029 [error] <0.453.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 CRASH REPORT Process 'Elixir.RabbitChat.OTP.DynamicConsumerManager' with 0 neighbours crashed with reason: no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48
2021-09-15 22:30:01.030 [error] <0.451.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.DynamicConsumerManager' started with 'Elixir.RabbitChat.OTP.DynamicConsumerManager':start_link([]) at <0.453.0> exit with reason no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48 in context child_terminated
2021-09-15 22:30:26.361 [error] <0.634.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 gen_server 'Elixir.RabbitChat.OTP.DynamicConsumerManager' terminated with reason: no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48
2021-09-15 22:30:26.362 [error] <0.634.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 CRASH REPORT Process 'Elixir.RabbitChat.OTP.DynamicConsumerManager' with 0 neighbours crashed with reason: no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48
2021-09-15 22:30:26.362 [error] <0.451.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.DynamicConsumerManager' started with 'Elixir.RabbitChat.OTP.DynamicConsumerManager':start_link([]) at <0.634.0> exit with reason no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48 in context child_terminated
2021-09-15 22:30:26.514 [error] <0.638.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 gen_server 'Elixir.RabbitChat.OTP.DynamicConsumerManager' terminated with reason: no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48
2021-09-15 22:30:26.516 [error] <0.638.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 CRASH REPORT Process 'Elixir.RabbitChat.OTP.DynamicConsumerManager' with 0 neighbours crashed with reason: no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48
2021-09-15 22:30:26.516 [error] <0.451.0>@Elixir.RabbitChat.OTP.DynamicConsumerManager:handle_continue:48 Supervisor 'Elixir.RabbitChat.Supervisor' had child 'Elixir.RabbitChat.OTP.DynamicConsumerManager' started with 'Elixir.RabbitChat.OTP.DynamicConsumerManager':start_link([]) at <0.638.0> exit with reason no match of right hand value {error,{already_started,<0.621.0>}} in 'Elixir.RabbitChat.OTP.DynamicConsumerManager':handle_continue/2 line 48 in context child_terminated
2021-09-15 22:44:28.941 [error] <0.772.0>@observer_wx:init:106 CRASH REPORT Process <0.772.0> with 0 neighbours exited with reason: bad argument in call to erlang:register(observer, <0.772.0>) in observer_wx:init/1 line 106
2021-09-15 22:46:39.697 [error] <0.454.0> Supervisor 'Elixir.RabbitChat.OTP.ConsumerDynSup' had child undefined started with 'Elixir.RabbitChat.OTP.PrivateConsumer':start_link([{user,<<"c">>},{web_pid,<0.645.0>}]) at <0.646.0> exit with reason normal in context child_terminated
2021-09-15 22:59:12.677 [error] <0.656.0> gen_server <0.656.0> terminated with reason: {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"c">>,<0.656.0>},5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 22:59:12.711 [error] <0.656.0> CRASH REPORT Process <0.656.0> with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"c">>,<0.656.0>},5000]}} in 'Elixir.GenServer':call/3 line 1024
2021-09-15 22:59:12.711 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.656.0> exit with reason {timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"c">>,<0.656.0>},5000]}} in context child_terminated
2021-09-15 22:59:20.988 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: {{{{timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"a">>,<0.663.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"...">>,...},...}},...},...]}},...},...}
2021-09-15 22:59:21.005 [error] <0.663.0> Cowboy stream 3 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.639.0> had its request process exit with reason: {{{timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"a">>,<0.663.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en...">>,...},...}},...},...]}},...}
2021-09-15 22:59:31.946 [error] <0.669.0> CRASH REPORT Process <0.669.0> with 0 neighbours exited with reason: {{{{timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"a">>,<0.669.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"...">>,...},...}},...},...]}},...},...}
2021-09-15 22:59:31.946 [error] <0.669.0> Cowboy stream 4 with ranch listener 'Elixir.RabbitChatWeb.Endpoint.HTTP' and connection process <0.639.0> had its request process exit with reason: {{{timeout,{'Elixir.GenServer',call,['Elixir.RabbitChat.OTP.DynamicConsumerManager',{report_pid,<<"a">>,<0.669.0>},5000]}},{'Elixir.RabbitChatWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en...">>,...},...}},...},...]}},...}
2021-09-15 23:03:11.335 [error] <0.633.0>@Elixir.Phoenix.LiveView.Channel:handle_info:250 gen_server <0.633.0> terminated with reason: call to undefined function 'Elixir.RabbitChatWeb.ChatterLive.Chat':handle_info/2 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 250
2021-09-15 23:03:11.414 [error] <0.633.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:handle_info CRASH REPORT Process <0.633.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RabbitChatWeb.ChatterLive.Chat':handle_info({new_message,<<"test">>}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},current_chatter => ...,...},...})
2021-09-15 23:03:11.415 [error] <0.513.0>@Elixir.RabbitChatWeb.ChatterLive.Chat:handle_info Supervisor {<0.513.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.633.0> exit with reason call to undefined function 'Elixir.RabbitChatWeb.ChatterLive.Chat':handle_info({new_message,<<"test">>}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{'__changed__' => #{},current_chatter => ...,...},...}) in context child_terminated
2021-09-15 23:06:47.657 [error] <0.612.0> gen_server <0.612.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-09-15 23:06:47.675 [error] <0.612.0> CRASH REPORT Process <0.612.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-09-15 23:06:47.675 [error] <0.495.0> Supervisor {<0.495.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.612.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.RabbitChat.ChatContext.Chatter',last_login => nil,name => <<"a">>,status => nil}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2021-09-16 10:10:22.976 [error] <0.481.0> gen_server <0.481.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2021-09-16 10:10:22.987 [error] <0.481.0> CRASH REPORT Process <0.481.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2021-09-16 10:10:22.987 [error] <0.480.0> Supervisor {<0.480.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link('Elixir.AMQP.SelectiveConsumer', <0.450.0>, {<<"client 192.168.0.10:38800 -> 3.67.177.249:5672">>,1}) at <0.481.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2021-09-16 10:10:22.987 [error] <0.480.0> Supervisor {<0.480.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link('Elixir.AMQP.SelectiveConsumer', <0.450.0>, {<<"client 192.168.0.10:38800 -> 3.67.177.249:5672">>,1}) at <0.481.0> exit with reason reached_max_restart_intensity in context shutdown
2021-09-16 10:10:23.017 [error] <0.450.0> gen_server 'Elixir.AMQP.Application.Channel::private_chat_consume_channel' terminated with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.680.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-16 10:10:23.020 [error] <0.450.0> CRASH REPORT Process 'Elixir.AMQP.Application.Channel::private_chat_consume_channel' with 0 neighbours exited with reason: {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.680.0>,open,70000]}} in gen_server:call/3 line 247
2021-09-16 10:10:23.020 [error] <0.446.0> Supervisor 'Elixir.AMQP.Application' had child 'Elixir.AMQP.Application.Channel::private_chat_consume_channel' started with 'Elixir.AMQP.Application.Channel':start_link([{connection,sub_tcp_connection},{proc_name,private_chat_consume_channel}]) at <0.450.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,504,<<"CHANNEL_ERROR - second 'channel.open' seen">>}}},{gen_server,call,[<0.680.0>,open,70000]}} in context child_terminated
